import Facebook_Hedder from "@/components/Facebook_Hedder";
import Facebook_Left_Side from "@/components/Facebook_Left_Side";
import Facebook_Middle_Side from "@/components/Facebook_Middle_Side";
import Facebook_Right_Side from "@/components/Facebook_Right_Side";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <Facebook_Hedder />
        <div className="min-h-screen max-w-screen   flex justify-between caret-transparent">
          <Facebook_Left_Side />

          <Facebook_Middle_Side />

          <Facebook_Right_Side />
        </div>
      </>
    </>
  );
}
