import Facebook_Hedder from "@/components/Facebook_Hedder";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <Facebook_Hedder />
        <div className="min-h-screen max-w-screen   flex flex-col items-center justify-center">
          <div></div>
          <div></div>
          <div></div>
        </div>
      </>
    </>
  );
}
